apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: aws-load-balancer-controller
deploy:
  helm:
    releases:
      - name: aws-load-balancer-controller
        namespace: kube-system
        createNamespace: false
        remoteChart: eks/aws-load-balancer-controller
        version: "1.14.1"
        valuesFiles:
          - values.yaml
    flags:
      upgrade:
        - --install
        - --reset-values
    hooks:
      before:
        - host:
            command:
              - "sh"
              - "-c"
              - "helm repo add eks https://aws.github.io/eks-charts --force-update"
            os: [darwin, linux]
        - host:
            command:
              - "sh"
              - "-c"
              - "./pre-install.sh"
            os: [darwin, linux]