apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: swishkube-otel-collector
deploy:
  helm:
    releases:
      - name: swishkube-otel-collector
        namespace: swish-analytics
        createNamespace: true
        remoteChart: open-telemetry/opentelemetry-collector
        version: "0.130.0"
        valuesFiles:
          - values.yaml
    flags:
      upgrade:
        - --install
    hooks:
      before:
        - host:
            command:
              - "sh"
              - "-c"
              - "helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts --force-update"
            os: [darwin, linux]
        - host:
            command:
              - "sh"
              - "-c"
              - "./pre-install.sh"
            os: [darwin, linux]