apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sts-certmanager-cert
  namespace: minio-operator
spec:
  dnsNames:
    - sts
    - sts.minio-operator.svc
    - sts.minio-operator.svc.cluster.local
  secretName: sts-tls
  issuerRef:
    name: minio-operator-ca-issuer


# Important: The spec.secretName is not optional. The secret name must be sts-tls.
# Ref: https://docs.min.io/community/minio-object-store/operations/cert-manager/cert-manager-operator.html#create-tls-certificate