#!/bin/bash
set -e

namespace='swish-analytics'
kubectl create namespace "${namespace}" || true
kubectl config set-context --current --namespace="${namespace}"

kubectl apply -f cluster/swish-analytics/intermediate-ca.certificate.yaml
kubectl apply -f cluster/swish-analytics/ca.issuer.yaml
kubectl apply -f cluster/swish-analytics/broker.certificate.yaml

# Making sure the secret generated by the certificate is ready before proceeding
kubectl wait --for=condition=Ready --timeout=60s certificate/kafka-broker-certificate

kubectl apply -f cluster/swish-analytics/nodepool.yaml
kubectl apply -f cluster/swish-analytics/kafka.yaml
kubectl apply -f cluster/swish-analytics/topic.yaml
kubectl apply -f cluster/swish-analytics/user.yaml