apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: hyperdx
deploy:
  helm:
    releases:
      - name: hyperdx
        namespace: swish-analytics
        createNamespace: true
        remoteChart: hyperdx/hdx-oss-v2
        version: "0.7.2"
        valuesFiles:
          - values.yaml
    flags:
      upgrade:
        - --install
    hooks:
      before:
        - host:
            command:
              - "sh"
              - "-c"
              - "helm repo add hyperdx https://hyperdxio.github.io/helm-charts --force-update"
            os: [darwin, linux]
        - host:
            command:
              - "sh"
              - "-c"
              - "./pre-install.sh"
            os: [darwin, linux]