apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-deployer
rules:
  - apiGroups: [""]
    resources: ["configmaps","secrets","services","serviceaccounts","events"]
    verbs: ["get","list","watch","create","update","patch","delete"]

  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets","daemonsets","replicasets"]
    verbs: ["get","list","watch","create","update","patch","delete"]

  - apiGroups: ["batch"]
    resources: ["jobs","cronjobs"]
    verbs: ["get","list","watch","create","update","patch","delete"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses","ingressclasses","networkpolicies"]
    verbs: ["get","list","watch","create","update","patch","delete"]

  - apiGroups: ["cert-manager.io"]
    resources: ["certificates","issuers"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-deployer-binding
  namespace: swish-analytics
subjects:
- kind: Group
  name: github-actions-deployer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: github-actions-deployer
  apiGroup: rbac.authorization.k8s.io