apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: altinity-clickhouse-operator
deploy:
  helm:
    releases:
      - name: altinity-clickhouse-operator
        namespace: swish-analytics
        createNamespace: true
        remoteChart: altinity-docs/altinity-clickhouse-operator
        version: "0.25.2"
        valuesFiles:
          - values.yaml
    flags:
      upgrade:
        - --install
    hooks:
      before:
        - host:
            command:
              - "sh"
              - "-c"
              - "helm repo add altinity-docs https://docs.altinity.com/clickhouse-operator --force-update"
            os: [darwin, linux]