apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: minIO
deploy:
  helm:
    releases:
      - name: minio-operator
        namespace: minio-operator
        createNamespace: true
        remoteChart: minio-operator/operator
        version: "7.1.1"
        valuesFiles:
          - values.yaml
    flags:
      upgrade:
        - --install
    hooks:
      before:
        - host:
            command:
              - "sh"
              - "-c"
              - "helm repo add minio-operator https://operator.min.io --force-update"
            os: [darwin, linux]
        - host:
            command:
              - "sh"
              - "-c"
              - "./pre-install.sh"
            os: [darwin, linux]